config/routes.rb
Rails.application.routes.draw do
  

  get 'cart/index'

  devise_for :users
  resources :items
  resources :charges
  resources :searches
  root 'pages#home'
  
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  
  get '/items' => 'items#index'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  get '/cart/checkout' => 'cart#checkout'
  
  
 
# youtube link https://www.youtube.com/watch?v=pNL4VPdru0Q

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def add
    id = params[:id]
    
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1
        
    redirect_to :action => :index
  end

  def index
    @cart = session[:cart] || {}
  end
  
  def clearCart
    session[:cart] = nil 
    redirect_to :action => :index
  end
  
  def change
  cart = session[:cart]
  id = params[:id];
  quantity = params[:quantity].to_i
  if cart and cart[id]
    unless quantity <= 0
      cart[id] = quantity
    else
      cart.delete id
    end
  end
    redirect_to :action => :index
  end
  
  def checkout
    session[:cart] = nil 
    redirect_to :action => :index
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  attr_accessor :amount
def new
end

def create 
  # Amount in cents
  @amount = 300

  customer = Stripe::Customer.create(
    :email => 'bruno@hardware.com',
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end
  
  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cart/index.html.erb
<div class="container">
<h1>Your Cart</h1>



<% total = 0 %>
	
<table class="cart">
    <tr>
        <td class="legend">Product</td>
        <td class="legend">Item</td>
        <td class="legend">Price</td>
        <td class="legend">Qty</td>
        <td class="legend">Total</td>
    </tr>
	
    <% @cart.each do | id, quantity | %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.title, item %></td>
        <td class="price"><%= number_to_currency(item.price) %></td>
        <td class="quantity"><%= quantity %><br /></td>
        <td class="price">
        <%= number_to_currency(quantity * item.price, :unit => "£") %>
    </td>
    </tr>
    <% total += quantity * item.price %>
    <% end %>

    <tr>
        <td colspan="4">
            <div class="total">Total:</div>
        </td>
        <td>
            <div class="price"><%= total=number_to_currency(total, :unit => "€") %></div>
        </td>
    </tr>
</table>
<br><br><br>

    <%= link_to 'Empty your Cart', cart_clear_path %>

<p>
     <%= link_to 'Continue Shopping', :controller => :items %>
</p>

<% if @cart.empty? %>
<p>Your Cart is empty.</p>
<% else %>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%= total %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="amount"
          data-locale="auto"></script>
          <% end %>
          
<% end %>

app/views/charges/create.html.erb
<h2>Thank you for your shopping</h2>

app/views/items/_form.html.erb
<div class="container">
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="catalog">
  <tr>
    <td>
  <div class="field">
    <%= f.label :title %>
    </td>
    <td>
    <%= f.text_field :title %>
  </div>
  </td>
  </tr>

<tr>
    <td>
  <div class="field">
    <%= f.label :description %>
    </td>
    <td>
    <%= f.text_area :description %>
  </div>
  </td>
  </tr>
<tr>
    <td>
  <div class="field">
    <%= f.label :price %>
    </td>
    <td>
    <%= f.text_field :price %>
  </div>
  </td>
  </tr>
<tr>
    <td>
  <div class="field">
    <%= f.label :image_url %>
    </td>
    <td>
    <%= f.text_field :image_url %>
  </div>
  </td>
  </tr>
<tr>
    <td>
  <div class="field">
    <%= f.label :category %>
    </td>
    <td>
    <%= f.text_field :category %>
  </div>
  </td>
  </tr>
<tr>
    <td>
  <div class="field">
    <%= f.label :brand %>
    </td>
    <td>
    <%= f.text_field :brand %>
  </div>
  </td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/items/edit.html.erb
<div class="container">
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Catalog</h1>
    
<% @items.each do |item| %>
    <div class="col-sm-2">
      <div class="panel panel-success">
          <div class="panel-heading"><%= link_to item.title, item %></div>
          <div class="panel-body"><%= link_to (image_tag item.image_url, :style => "height:90px"), item %> </div>
          <div class="panel-footer"><%= link_to item.category, item %>
            </div>
          <div class="panel-footer">
            <h4><%= number_to_currency(item.price, :unit => "Price: ") %></h4>
          <div class="links">
                <% if user_signed_in? %>
                    <% if current_user.try(:admin?) %>
                         <%= link_to 'Edit', edit_item_path(item)%> |
                        <%= link_to 'Delete', item, :confirm => 'Are you sure?', :method => :delete %>
                    
                    <% end %>
                <% end %>
                <a href="/cart/<%= item.id %>"> Add to Cart</a>
           </div>
          </div>
      </div>
    </div>
<% end %>
</div>
<div class="container">
    <% if user_signed_in? %>
        <% if current_user.try(:admin?) %>
            <p><%= link_to 'New item', new_item_path %></p>
        <% end %>
    <% end %>
  </div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<table class="catalog">
  <tr>
    <td>
        <div>
        <div class="image">
            <%= link_to (image_tag @item.image_url, :style => "height:100px"), @item %>
        </div>
    </td>
    <td>
        <p>
          <strong>Title:</strong>
            <%= @item.title %>
        </p>
        
        <p>
          <strong>Description:</strong>
          <%= @item.description %>
        </p>
        
        <p>
          <strong>Price:</strong>
          <%= @item.price %>
        </p>
        
        <p>
          <strong>Category:</strong>
          <%= @item.category %>
        </p>
        
        <p>
          <strong>Brand:</strong>
          <%= @item.brand %>
        </p>
    </td>
  </tr>
  

</table>
<% if user_signed_in? %>
        <% if current_user.try(:admin?) %>
          <%= link_to 'Edit', edit_item_path(@item) %> |
          <%= link_to 'Back', items_path %>
        <% end %>
<% end %>
<a href="/cart/<%= @item.id %>">Add to Cart</a><br><br>
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
   
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
   
     .jumbotron {
      margin-bottom: 0;
       background-image: url("/assets/header.jpg");
    }
    
    footer {
      background-color: #c2c2a3;
      padding: 15px;
    }
  
  </style>
  </head>

  <body>
    <div class="jumbotron">
  <div class="container text-center">
    <h1>Locks and Hardware's </h1>      
  </div>
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="collapse navbar-collapse " id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home</a></li>
        <li><a href="/items">Products</a></li>
        <li><a href="/about">About Us</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Account
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Edit My Account",edit_user_registration_path%></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
      </li>
         <% else %>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li> <%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
              <li><a href="/cart"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <h2>EXPRESS YOURSELF BOLDLY WITH DUBLIN’S BEST DOOR FITTINGS SPECIALIST</h2>
              <p>Locks and Hardware’s passion is to facilitate bringing your personal style to your home. Our door products are more than about just opening, closing and securing your environment. We believe than our products should express your personality and bring your home to life. Our motto is “Express yourself boldly with Locks and Hardware”.</p>
              <p>Locks and Hardware items have been rigorously tested and designed with meticulous detail. Every time a customer orders an item is custom-crafted on site in our Walkinstown facility. As our valued customer you can specify your own customisations and finishes. We pride ourselves in a turnaround of three days from receipt of order to delivery straight to your home.</p>
              <p>Establish in 1967, Locks and Hardware has been at the vanguard of cutting edge door furniture for nearly half a century. Ever searching for the finest door fittings trend, we work tirelessly tobalance functionality with style. You will find the just the item you need,be it modern, classic or heritage-orientated.</p>
              <p>We are delighted that you have taken the time to visit our site and hopethat you will stay with us on this door apparel voyage for many years to come and when it comes to door fittings, the first thing that will come to mind is: “My friends in Walkinstown, Locks and Hardware will have it!”</p>
            </div>
        </div>
</section>

app/views/pages/contact.html.erb
<section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <h2>PLEASE DO NOT HESITATE TO CONTACT US TODAY!</h2>
                <p>Our dedicated team of customer care executives are standing by right now for your call. Your can reach one of our operatives at (01) 419 8778 anytime between 9 and 6, Monday to Friday.</p>
                <p>Alternatively please feel free to visit our showroom in person at our facility in Merrywell Business Park in South-West Dublin. An easy way to find usis to navigate to the LUAS Red Cow stop on the Red Line and continue down by the hotel and bridge towards the Harley Davidson store. We are located down the next road on the left.</p>
                <p>We also welcome emails including any requests or comments, good or bad, that you may have. Please reach out to us at locksandhardware@locksandhardware.com.</p>
                <p>Address: Unit B, Merrywell Business Park, Ballymount Rd Lower, Dublin</p>
                <p>Phone: (01) 419 8778</p>
                <p>Email: locksandhardware@locksandhardware.com</p>
            </div>
        </div>
</section>

app/views/pages/home.html.erb
<section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <h2>THE FINEST DOOR HARDWARE RESOURCE IN DUBLIN</h2>
              <p>We hope you find what you are looking for here at our site. Our full portfolio of door furniture items, the Heritage Door Furniture Suite comprises four distinct collections. Please read on for more details.</p>
              <p>The Banville Door Handle Collection collates the finest door handle technology available today. Crafted from the finest alloys and materials you will find the standard of craftsmanship second to none.</p>
              <p>The Bowen Door Knob Collection gathers together our finest offering of door knobs to date. Designed with an almost obsessive eye for detail, the Bowen Collection has the door knob that will complement and bring admiration to any home’s door.</p>
              <p>The McCourt Latches and Locks Collection brings fuses functionality and durability in our world class standard door security items.</p>
              <p>And finally the Kavanagh Hinges Collection offers you high-end hinges ranging from piano hinges to washered and plain-bearing pieces. Don’t compromise with door hinges with our Kavanagh Collection.</p>
            </div>
        </div>
</section>